name: Build & Deploy Hakyll Site

on:
  push:
    branches: [ main ]   # change if your default branch is different
  workflow_dispatch:

permissions:
  contents: write   # required for gh-pages push

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Haskell (GHC + cabal)
        id: haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.6.7"        # pin GHC
          cabal-version: "3.12.1.0"   # pin cabal-install
          cabal-update: false         # we rely on your pinned index-state

      - name: Enable ghcup download cache
        run: |
          mkdir -p ~/.ghcup
          printf "cache: true\n" >> ~/.ghcup/config.yaml

      - name: Cache ghcup tarballs + cabal store
        uses: actions/cache@v4
        with:
          path: |
            ~/.ghcup/cache
            ${{ steps.haskell.outputs.cabal-store }}
          key: cabal-${{ runner.os }}-ghc${{ steps.haskell.outputs.ghc-version }}-cabal${{ steps.haskell.outputs.cabal-version }}-${{ hashFiles('**/*.cabal', 'cabal.project', 'cabal.project.freeze') }}
          restore-keys: |
            cabal-${{ runner.os }}-ghc${{ steps.haskell.outputs.ghc-version }}-cabal${{ steps.haskell.outputs.cabal-version }}-

      - name: Show tool versions
        run: |
          ghc --version
          cabal --version

      # Ensure the freeze file is respected automatically by v2-build
      - name: Build site executable
        run: cabal build all

      - name: Build static site
        # change "site" to your executable name if different
        run: cabal run conversations -- build
        env:
          # Optional: if your generator needs locale for UTF-8 paths
          LANG: en_US.UTF-8

      - name: Suppress Jekyll
        run: touch _site/.nojekyll

      # If you need a CNAME, copy it into _site/ before this step.
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          # Optional hardening:
          # user_name: github-actions[bot]
          # user_email: 41898282+github-actions[bot]@users.noreply.github.com
